name: wherehous
description: A new Flutter project.

dependencies:
  sqflite: "^0.8.9" #all sql packages benefit from this
  async: "^2.0.6"
  path_provider: "^0.4.0"
  image_picker: "^0.4.1"
  
  ssrp: "^0.3.0" # experimental

  geolocation: ^0.2.1

  #SQL solution dependencies
  sqljocky5: "^1.0.0" ## sketchy version and flutter won't work with the safer newer ones
  crypto: "^2.0.2+1" 
  logging: "^0.11.3+1"
  collection: "^1.14.6"
  convert: "^2.0.1"
  typed_data: "^1.1.5"
  charcode: "^1.1.1"
  map_view: "^0.0.12"

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
          
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

